language: ruby
rvm:
  - 1.9.3
before_script:
  - mysql -e 'create database myapp_test;'
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:drop --trace
  - bundle exec rake db:create --trace
  - bundle exec rake db:migrate --trace
script:
  - RAILS_ENV=test bundle exec rake spec
notifications:
  email:
    - jeff@hearthstats.net